### ISSUE TITLE
Upwork: TypeScript Next.js Project

### ISSUE THREAD

**Issue by niravswami** [therockstarind/rdrive#25]
Hi i have seen your posting on Upwork.
After examine you log, you can see this line `TypeError: Cannot read properties of undefined (reading 'toLowerCase')  ` and trace that `Import trace for requested module:` , the issue could be in your `@fortawesome/fontawesome-svg-core/styles.css` fontawesome package.  
one solution is you can try `yarn`  instead of `npm`. i mean to say install all the dependancies with `yarn`.  yarn also install `peer dependencies` and other stuffs. 

I am unable to run your code   because `SUPABASE` dependancy. if you give me .env file I can try to resolved it. is there any other issue you can contact me:
LinkedIn: https://www.linkedin.com/in/nirav-swami-9a628945/

Thanks 
Nirav

**Comment by KudryashovAV** [comment]
Hi! The same. Also, I found a few type issues during `pnpm run build`.  So, maybe we can fix a batch of issues. But, yes - without some ENV variables, it is impossible to run the app. [My profile on LinkedIn](https://www.linkedin.com/in/alexey-kudryashov-27321056/)

**Comment by therockstarind** [comment]
> Hi i have seen your posting on Upwork.
> After examine you log, you can see this line `TypeError: Cannot read properties of undefined (reading 'toLowerCase')  ` and trace that `Import trace for requested module:` , the issue could be in your `@fortawesome/fontawesome-svg-core/styles.css` fontawesome package.  
> one solution is you can try `yarn`  instead of `npm`. i mean to say install all the dependancies with `yarn`.  yarn also install `peer dependencies` and other stuffs. 
> 
> I am unable to run your code   because `SUPABASE` dependancy. if you give me .env file I can try to resolved it. is there any other issue you can contact me:
> LinkedIn: https://www.linkedin.com/in/nirav-swami-9a628945/
> 
> Thanks 
> Nirav

same problem with yarn btw we were running our project with pnpm

**Comment by therockstarind** [comment]
> Hi! The same. Also, I found a few type issues during `pnpm run build`.  So, maybe we can fix a batch of issues. But, yes - without some ENV variables, it is impossible to run the app. [My profile on LinkedIn](https://www.linkedin.com/in/alexey-kudryashov-27321056/)
> 
> 

to run project .env is not mandatory project can still run but the problem is something else 4 day's ago it's working good i just changed the pc after that getting this problem.

**Comment by therockstarind** [comment]
can't create stubbed version of env bcz this project is live and do all of things its really hard as beginner so please understand that.

and for the problem solution i think this problem in my pc with windows 11 bcz when i run the project on Codespaces its working fine. on that.

**Comment by alvir** [comment]
@therockstarind I came up with an idea about Docker way to be sure that the issue is in your environment.

**Comment by therockstarind** [comment]
@alvir Bro project is running with same environment variables on [Vercel](rdrive.org) then how it can be problem on environment??

**Comment by alvir** [comment]
vercel does not use Windows 11

**Comment by therockstarind** [comment]
true 😶

**Comment by therockstarind** [comment]
after reinstall window 11 with older version problem got solved. 
finally
